// Code generated by generate.go. DO NOT EDIT.

package sa4003

import (
	"testing"

	"github.com/Le-BlitzZz/go-tools/analysis/lint/testutil"
)

func TestTestdata(t *testing.T) {
	testutil.Run(t, SCAnalyzer)
}
