// Code generated by generate.go. DO NOT EDIT.

package quickfix

import (
	"github.com/Le-BlitzZz/go-tools/analysis/lint"
	"github.com/Le-BlitzZz/go-tools/quickfix/qf1001"
	"github.com/Le-BlitzZz/go-tools/quickfix/qf1002"
	"github.com/Le-BlitzZz/go-tools/quickfix/qf1003"
	"github.com/Le-BlitzZz/go-tools/quickfix/qf1004"
	"github.com/Le-BlitzZz/go-tools/quickfix/qf1005"
	"github.com/Le-BlitzZz/go-tools/quickfix/qf1006"
	"github.com/Le-BlitzZz/go-tools/quickfix/qf1007"
	"github.com/Le-BlitzZz/go-tools/quickfix/qf1008"
	"github.com/Le-BlitzZz/go-tools/quickfix/qf1009"
	"github.com/Le-BlitzZz/go-tools/quickfix/qf1010"
	"github.com/Le-BlitzZz/go-tools/quickfix/qf1011"
	"github.com/Le-BlitzZz/go-tools/quickfix/qf1012"
)

var Analyzers = []*lint.Analyzer{
	qf1001.SCAnalyzer,
	qf1002.SCAnalyzer,
	qf1003.SCAnalyzer,
	qf1004.SCAnalyzer,
	qf1005.SCAnalyzer,
	qf1006.SCAnalyzer,
	qf1007.SCAnalyzer,
	qf1008.SCAnalyzer,
	qf1009.SCAnalyzer,
	qf1010.SCAnalyzer,
	qf1011.SCAnalyzer,
	qf1012.SCAnalyzer,
}
